---
lug_groups: |
  {
    {%- for var in vars | dict2items -%}
      {%- if var.key | regex_search('^group_') is not none
        and (
          var.value | type_debug == "dict"
          or var.value | type_debug == "AnsibleMapping"
        ) -%}
        {%- set group_name = var.key | regex_replace('^group_', '') -%}
        {%- set preferred_domain = var.value.preferred_domain | default((var.value.dns_key | default(group_name)) + '.lug.org.uk') -%}
        "{{ group_name }}": {

          "preferred_domain": "{{ preferred_domain }}",

          {%- if lugmasters[group_name] is defined -%}
            "admins": {{ lugmasters[group_name] }},
          {%- endif -%}

          {%- if var.value.state is not defined -%}
            "state": "error",
          {%- endif -%}

          {%- if var.value.hosting is not defined -%}
            "hosting": "snm",
          {%- endif -%}

          {%- if var.value.web is not defined -%}
            "web": "static",
          {%- endif -%}

          {%- if var.value.serveralias is not defined -%}
            "serveralias": [
              {%- for suffix in ['.lug.org.uk','.glug.org.uk','.lugs.org.uk'] -%}
                {%- if preferred_domain | regex_search(group_name + suffix) is none -%}
                  "{{ group_name }}{{ suffix }}",
                  "www.{{ group_name }}{{ suffix }}",
                {%- else -%}
                  {%- if preferred_domain | regex_search('www.' + group_name + suffix) is none -%}
                    "www.{{ group_name }}{{ suffix }}",
                  {%- else -%}
                    "{{ group_name }}{{ suffix }}",
                  {%- endif -%}
                {%- endif -%}
              {%- endfor -%}
            ],
          {%- endif -%}

          {%- for item in var.value | dict2items -%}
            {%- if item.key != 'preferred_domain' -%}
              "{{ item.key }}":
              {%- if item.value | type_debug not in ['dict', 'list'] -%}"{%- endif -%}
                {{ item.value }}
              {%- if item.value | type_debug not in ['dict', 'list'] -%}"{%- endif -%},
            {%- endif -%}
          {%- endfor -%}
        },
      {%- endif -%}
    {%- endfor -%}
  }
